LANGUAGES = {
    "en": {
        "title": "DefaceIT - Video Face & License Plate Blurring",
        "input_video": "Input Video:",
        "output_video": "Output Video:",
        "browse": "Browse...",
        "settings": "Settings",
        "blur_strength": "Blur Strength:",
        "confidence": "Confidence:",
        "blur_type": "Blur Type:",
        "gaussian": "Gaussian",
        "pixelate": "Pixelate",
        "detect": "Detect:",
        "faces": "Faces",
        "license_plates": "License Plates",
        "device": "Device:",
        "auto": "Auto",
        "cpu": "CPU",
        "gpu": "GPU",
        "audio_pitch_shift": "Audio Pitch Shift",
        "pitch_semitones": "Pitch (semitones):",
        "preview_audio": "Preview Audio",
        "stop_preview": "Stop Preview",
        "progress": "Progress:",
        "ready": "Ready",
        "start_processing": "Start Processing",
        "cancel": "Cancel",
        "credits": "Credits",
        "developer": "Developer:",
        "website": "Website:",
        "telegram": "Telegram:",
        "donate_crypto": "Donate (Crypto):",
        "donate_card": "Donate (Card):",
        "language": "Language:",
        "english": "English",
        "persian": "Persian",
        "error_no_input": "Please select an input video file",
        "error_no_output": "Please select an output video file",
        "error_file_not_found": "Input file does not exist",
        "error_preview_no_file": "Please select an input video file first",
        "info_no_pitch": "Pitch shift is 0.0 - no change to preview",
        "success_complete": "Video processing complete!",
        "processing_speed": "Processing speed:",
        "fps": "FPS",
    },
    "fa": {
        "title": "DefaceIT - تار کردن چهره و پلاک در ویدیو",
        "input_video": "ویدیوی ورودی:",
        "output_video": "ویدیوی خروجی:",
        "browse": "مرور...",
        "settings": "تنظیمات",
        "blur_strength": "قدرت تار کردن:",
        "confidence": "اعتماد:",
        "blur_type": "نوع تار کردن:",
        "gaussian": "گاوسی",
        "pixelate": "پیکسلی",
        "detect": "تشخیص:",
        "faces": "چهره‌ها",
        "license_plates": "پلاک‌ها",
        "device": "دستگاه:",
        "auto": "خودکار",
        "cpu": "پردازنده",
        "gpu": "کارت گرافیک",
        "audio_pitch_shift": "تغییر زیر و بم صدا",
        "pitch_semitones": "زیر و بم (نیم‌پرده):",
        "preview_audio": "پیش‌نمایش صدا",
        "stop_preview": "توقف پیش‌نمایش",
        "progress": "پیشرفت:",
        "ready": "آماده",
        "start_processing": "شروع پردازش",
        "cancel": "لغو",
        "credits": "اعتبارات",
        "developer": "توسعه‌دهنده:",
        "website": "وب‌سایت:",
        "telegram": "تلگرام:",
        "donate_crypto": "حمایت (ارز دیجیتال):",
        "donate_card": "حمایت (کارت):",
        "language": "زبان:",
        "english": "انگلیسی",
        "persian": "فارسی",
        "error_no_input": "لطفا یک فایل ویدیوی ورودی انتخاب کنید",
        "error_no_output": "لطفا یک فایل ویدیوی خروجی انتخاب کنید",
        "error_file_not_found": "فایل ورودی وجود ندارد",
        "error_preview_no_file": "لطفا ابتدا یک فایل ویدیوی ورودی انتخاب کنید",
        "info_no_pitch": "تغییر زیر و بم 0.0 است - تغییری در پیش‌نمایش نیست",
        "success_complete": "پردازش ویدیو کامل شد!",
        "processing_speed": "سرعت پردازش:",
        "fps": "فریم بر ثانیه",
    }
}

CREDITS = {
    "developer": "Shin",
    "x": "https://x.com/hey_itsmyturn",
    "website": "https://sh1n.org",
    "telegram": "https://t.me/itsthealephyouknowfromtwitter",
    "donate_crypto": "https://nowpayments.io/donation/shin",
    "donate_card": "https://buymeacoffee.com/hey_itsmyturn"
}

